### ISSUE TITLE
Ask for Position

### ISSUE THREAD

**Issue by Cal-Hagner** [Team-501-The-PowerKnights/Scouting-App#11]
Prompt user for position (Red1, Red2, Red3, Blue1, Blue2, Blue3) and save it to shared_preferences when done.

**Comment by Cal-Hagner** [comment]
@Matt-Gleich What do you think for design of this? 6 separate buttons, one selector for color and one for position? Something completely different?

**Comment by gleich** [comment]
Two columns in a row. Each button is rounded like the button on the greeting screen. Make a PR draft once you make your first commit. So I know you started on it.
