### ISSUE TITLE
Create Setup Screen and Process

### ISSUE THREAD

**Issue by gleich** [Team-501-The-PowerKnights/Scouting-App#6]
- Only be shown when the app is first downloaded.
- Greet the user
- Ask for the following information:
    - Position (Red1, Red2, Red3, Blue1, Blue2, Blue3)
    - Team Number
    - Theme

When this is done write data to shared settings and pop and push to the main route

**Comment by Cal-Hagner** [comment]
Does team number refer to the team bring scouted or the team doing the scouting?

**Comment by gleich** [comment]
This is the setup screen so it is the team doing the scouting. I already started work on this in the setup screen branch. @Cal-Hagner Please do not make any changes until tomorrow's meeting.
